name: Latest medium workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-medium:
    name: Update this repo's README with latest blog posts in medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
         comment_tag_name: "MEDIUM"
         commit_message: "Updated readme with the latest Medium data"
         feed_list: "https://medium.com/feed/@bhageshhunakunti"
